kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: nextcloud
  name: nextcloud
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "local-lvm"
