apiVersion: v1
kind: Service
metadata:
  namespace: nextcloud
  labels:
    app: nextcloud
    app.kubernetes.io/name: nextcloud
  name: nextcloud
spec:
  type: LoadBalancer
  loadBalancerIP: <YOUR_IP>
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nextcloud
